# Version of Docker-compose
version: '1.0'
services:

  node:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_francoC
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_FrancoC
    ports:
      - '3001:3000'
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules